spring:

  profiles:
    active: dev


  data:
    mongodb:
      uri: mongodb+srv://codesrhereaman:Amanph%409368@cluster0.18g5fbp.mongodb.net/?appName=Cluster0
      database: journalApp
      auto-index-creation: true
      username: journalApp
      password: journalApp


logging:
  level:
    net:
      coderrhereaman:
        jounalApp:
          services:
            JournalEntryService: TRACE




  #server:
  #      port: 6969

  #4 ways to configure the port or profiles
  #using application.properties
  #using application.yml
  #using terminal
  #using configuration edit
  #using vm (java -Dserver.port=1111 -jar journalApp-0.0.1-SNAPSHOT.jar )