#spring.application.name=journalApp
##spring.data.mongodb.host=localhost
##spring.data.mongodb.port=27017
#spring.data.mongodb.database=journalApp
#spring.data.mongodb.uri=mongodb+srv://codesrhereaman:Amanph%409368@cluster0.18g5fbp.mongodb.net/?appName=Cluster0
#spring.data.mongodb.auto-index-creation=true
##spring.data.mongodb.username=journalApp
##spring.data.mongodb.password=journalApp